version: "3.8"

services:
  db:
    image: postgres:11-alpine

    env_file:
      - ./.env

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .

    env_file:
      - ./.env

    volumes:
      - .:/code

      # o volume garante que as alterações realizadas no projeto sejam propagadas no container

    ports:
      - "8001:8001"

    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
